version: '3.7'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    tty: true
    stdin_open: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitor
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    network_mode: host
    volumes:
      - '/:/host:ro,rslave'
    
  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    command:
      - '--procfs=/host/proc'
      - '--config.path=/config/process-exporter.yml'
    pid: host
    volumes:
      - /proc:/host/proc:ro,rslave
      - ./process-exporter/process-exporter.yml:/config/process-exporter.yml
    ports:
      - 9256:9256
    networks:
      - monitor
    privileged: true


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitor
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      - cadvisor
      - node-exporter
      - process-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: ${UID}
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitor
    depends_on:
      - prometheus

networks:
  monitor:
    driver: bridge
