global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['0.0.0.0:9090']

  - job_name: node
    static_configs:
    - targets: ['host.docker.internal:9100']
  
  - job_name: gpu
    static_configs:
    - targets: ['nvidia-gpu-exporter:9835']

  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']